module.exports = {
    SET_USER_INFO: "SET_USER_INFO",
    SET_CURRENT_DSL_ACCOUNT: "SET_CURRENT_DSL_ACCOUNT",
    SET_ALL_DSL_ACCOUNTS: "SET_ALL_DSL_ACCOUNTS",
    SET_ALL_DEVICES: "SET_ALL_DEVICES",
    SET_CURRENT_DSL_ACCOUNT_NAME: "SET_CURRENT_DSL_ACCOUNT_NAME",
    SET_EDNS_STATUS_OF_ACCOUNT: "SET_EDNS_STATUS_OF_ACCOUNT",
    SET_INTERNET_STATUS_OF_ACCOUNT: "SET_INTERNET_STATUS_OF_ACCOUNT",
    SET_INTERNET_STATUS_OF_DEVICE: "SET_INTERNET_STATUS_OF_DEVICE",
    SET_CURRENT_DEVICE_ID: "SET_CURRENT_DEVICE_ID",
    UPDATE_DEVICE_NAME: "UPDATE_DEVICE_NAME",
    SET_DEVICE_RESTRICTIONS: "SET_DEVICE_RESTRICTIONS",
    DELETE_DEVICE_FROM_DSL_ACCOUNT: "DELETE_DEVICE_FROM_DSL_ACCOUNT",
    SET_DEVICE_DOMAIN_RESTRICTIONS: "SET_DEVICE_DOMAIN_RESTRICTIONS",
    UPDATE_DEVICE_PHOTO: "UPDATE_DEVICE_PHOTO",
    SET_ALL_APPLICATIONS: "SET_ALL_APPLICATIONS",
    SET_ALL_CATEGORIES: "SET_ALL_CATEGORIES"
};
